In [1]:
from pyts.datasets import load_gunpoint
from pyts.classification import TimeSeriesForest
X_train, X_test, y_train, y_test = load_gunpoint(return_X_y=True)

In [2]:
X_train

array([[-0.6478854 , -0.64199155, -0.63818632, ..., -0.64042873,
        -0.63866571, -0.63865722],
       [-0.64442658, -0.64540093, -0.64705511, ..., -0.6349345 ,
        -0.6344968 , -0.63159565],
       [-0.77835282, -0.77827907, -0.77715084, ..., -0.70419626,
        -0.70760524, -0.7071202 ],
       ...,
       [-0.77912617, -0.77837863, -0.7757449 , ..., -0.50500603,
        -0.50373099, -0.50438486],
       [-0.70303339, -0.70261754, -0.70250356, ..., -0.64113375,
        -0.64140622, -0.64210896],
       [-1.4357199 , -1.4322717 , -1.4329285 , ..., -1.4354619 ,
        -1.4352821 , -1.4308845 ]])

In [17]:
import pickle
with open('/home/jh/2python_pr/CMEPredviaSF/Dataset_Creation/Timeseries_data.pickle', 'rb') as file:
        data = pickle.load(file)
        label = pickle.load(file)

In [18]:
data

array([[1.3773e-07, 1.3660e-07, 1.3200e-07, 1.3303e-07, 1.3580e-07,
        1.3094e-07, 1.2952e-07, 1.2687e-07, 1.2519e-07, 1.2536e-07,
        1.2567e-07, 1.2182e-07, 1.1722e-07, 1.1960e-07, 1.2465e-07,
        1.2890e-07, 1.3306e-07, 1.4098e-07, 1.6350e-07, 1.7810e-07,
        1.8717e-07, 2.0129e-07, 2.4429e-07, 3.2695e-07, 4.3685e-07,
        5.4268e-07, 6.3675e-07, 7.2129e-07, 7.8603e-07, 8.4541e-07,
        9.3018e-07, 1.0396e-06, 1.1705e-06, 1.3746e-06, 1.7213e-06,
        2.1633e-06, 2.6972e-06, 3.3155e-06, 3.9708e-06, 4.7776e-06,
        5.5581e-06, 6.3114e-06, 6.9930e-06, 7.7712e-06, 8.4639e-06,
        9.0681e-06],
       [1.4563e-07, 1.4398e-07, 1.4713e-07, 1.4607e-07, 1.4415e-07,
        1.5474e-07, 1.6456e-07, 1.7340e-07, 1.8483e-07, 1.9748e-07,
        2.0775e-07, 2.2704e-07, 2.4146e-07, 2.7978e-07, 2.9992e-07,
        3.0597e-07, 3.2155e-07, 3.3978e-07, 3.5606e-07, 3.5969e-07,
        3.8092e-07, 4.1967e-07, 4.7791e-07, 5.6587e-07, 6.9990e-07,
        8.8585e-07, 1.1327e

In [19]:
label

array([['M1.0', np.float64(84.79249098587123), np.float64(871.0)],
       ['C4.4', np.float64(32.752941322428434), np.float64(1205.0)],
       ['C1.5', np.float64(6.813742637026902), np.float64(403.0)],
       ['C4.5', np.float64(17.826662649503966), np.float64(1471.0)],
       ['C3.3', np.float64(39.61476179271544), np.float64(818.0)],
       ['C1.7', np.float64(15.476338931794308), np.float64(304.0)],
       ['C2.5', np.float64(18.916613209608627), np.float64(955.0)],
       ['C1.3', np.float64(8.995355658763142), np.float64(385.0)],
       ['C1.5', np.float64(15.93526057170348), np.float64(365.0)],
       ['M1.6', np.float64(78.05572819055948), np.float64(424.0)]],
      dtype=object)

In [14]:
import numpy as np
arr = np.empty((0,4), int)
arr = np.append(arr, np.array([[1,2,3]]), axis=0)
arr = np.append(arr, np.array([[4,5,6]]), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6]])